### ISSUE TITLE
Compilation failure on ubuntu 20.04 ros2 foxy

### ISSUE THREAD

**Issue by abdulmelikbekmez** [m-dahl/r2r_minimal_node#5]
On Ubuntu 20.04 which has ros2 foxy there is a linkage error:

note: /usr/bin/ld: cannot find -lbuiltin_interfaces__rosidl_typesupport_c
          /usr/bin/ld: cannot find -lbuiltin_interfaces__rosidl_typesupport_introspection_c
          /usr/bin/ld: cannot find -lbuiltin_interfaces__rosidl_generator_c
          /usr/bin/ld: cannot find -lunique_identifier_msgs__rosidl_typesupport_c
          /usr/bin/ld: cannot find -lunique_identifier_msgs__rosidl_typesupport_introspection_c
          /usr/bin/ld: cannot find -lunique_identifier_msgs__rosidl_generator_c
          /usr/bin/ld: cannot find -lr2r_minimal_node_msgs__rosidl_typesupport_c
          /usr/bin/ld: cannot find -lr2r_minimal_node_msgs__rosidl_typesupport_introspection_c
          /usr/bin/ld: cannot find -lr2r_minimal_node_msgs__rosidl_generator_c
          /usr/bin/ld: cannot find -lrcl_interfaces__rosidl_typesupport_c
          /usr/bin/ld: cannot find -lrcl_interfaces__rosidl_typesupport_introspection_c
          /usr/bin/ld: cannot find -lrcl_interfaces__rosidl_generator_c
          /usr/bin/ld: cannot find -laction_msgs__rosidl_typesupport_c
          /usr/bin/ld: cannot find -laction_msgs__rosidl_typesupport_introspection_c
          /usr/bin/ld: cannot find -laction_msgs__rosidl_generator_c
          /usr/bin/ld: cannot find -lstd_msgs__rosidl_typesupport_c
          /usr/bin/ld: cannot find -lstd_msgs__rosidl_typesupport_introspection_c
          /usr/bin/ld: cannot find -lstd_msgs__rosidl_generator_c
          /usr/bin/ld: cannot find -lrcl
          /usr/bin/ld: cannot find -lrcl_logging_spdlog
          /usr/bin/ld: cannot find -lrcl_yaml_param_parser
          /usr/bin/ld: cannot find -lrcutils
          /usr/bin/ld: cannot find -lrmw
          /usr/bin/ld: cannot find -lrosidl_typesupport_c
          /usr/bin/ld: cannot find -lrosidl_runtime_c
          collect2: error: ld returned 1 exit status
          

error: could not compile `r2r` due to previous error
make[2]: *** [CMakeFiles/cargo_target.dir/build.make:57: CMakeFiles/cargo_target] Error 101
make[1]: *** [CMakeFiles/Makefile2:79: CMakeFiles/cargo_target.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< r2r_minimal_node [0.48s, exited with code 2]

This error occurred in Docker container built with `ros:foxy` image. 

To reproduce this error

- `docker run --rm -it ros:foxy bash` to create container

- `apt update`
- `apt upgrade`
- `apt install curl` needed for rust installation
- `apt install libclang-dev` dependency for r2r package
- `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` rust installation
- `source "$HOME/.cargo/env"`
- `cd` navigate to home directory
- `mkdir src`
- `cd src`
- `git clone https://github.com/m-dahl/r2r_minimal_node.git`
- `cd ..`
- `colcon build`

**Comment by abdulmelikbekmez** [comment]
Hi,

Thanks for the quick reply.

If you're aware of the error, it's fine. r2r package is really cool. I really enjoyed using it. If there's anything I can help with, I'll be happy to help.

**Comment by m-dahl** [comment]
Thanks for the kind words! I took some time to look into why this problem occurs and it has to do with the default cmake version on ubuntu 20.04. I have added a note about it and how to fix it (update cmake) in the README. Closing this issue now.
