### ISSUE TITLE
How to add my rs file?

### ISSUE THREAD

**Issue by takahashi-e6** [m-dahl/r2r_minimal_node#6]
Hello
I would like to add my own rs file to the r2r_mininal_node package.
I'm trying to refer to the already existing main.rs, but I don't know how to do it.
Could you please tell me?

**Comment by m-dahl** [comment]
Are you wondering how to add an additional binary to the package? If so, you can install multiple binaries in CMakeLists.txt:
```
install(PROGRAMS
  ${CMAKE_SOURCE_DIR}/target/colcon/bin1
  ${CMAKE_SOURCE_DIR}/target/colcon/bin2
  ${CMAKE_SOURCE_DIR}/target/colcon/bin3
  DESTINATION lib/${PROJECT_NAME}
)
```
In cargo.toml define multiple binaries as well:
```
[[bin]]
name = "bin1"
path = "src/bin1.rs"

[[bin]]
name = "bin2"
path = "src/bin2.rs"

[[bin]]
name = "bin3"
path = "src/bin3.rs"

```

Then run with `ros2 run r2r_minimal_node bin1`

**Comment by takahashi-e6** [comment]
@m-dahl 
Thank you for your reply.
This is exactly what I wanted to know.

thanks
