### ISSUE TITLE
setup of rust-analyzer for generated message

### ISSUE THREAD

**Issue by huand** [m-dahl/r2r_minimal_node#7]
I'm using vscode with rust-analyzer, and I cannot get the autocompletion for message to work.

Any idea on how to setup rust-analyzer with r2r?

**Comment by huand** [comment]
for info, im in a devcontainer.

i used this setting

    "rust-analyzer.linkedProjects": [
        "/workspaces/r2r/src/r2r_minimal_node/r2r_minimal_node/Cargo.toml"
    ],

so rust-analyzer knows about the pkg in the ros workspace.
    
But i guess rust-analyzer also needs the ROS workspace to be sourced? how do we do that?

**Comment by huand** [comment]
also for info it works for
`r2r::std_msgs::msg::String` as i can do right click->go to definition, but not for `HelloWorld::Response`

**Comment by huand** [comment]
also when i do a rightclick->go to definition on `std_msgs` it brings me to 

`src/r2r_minimal_node/r2r_minimal_node/target/debug/build/r2r-baf33bf2d995a473/out/_r2r_generated_msgs.rs`

and indeed here there is no `r2r_minimal_node_msgs`

if i look for the `Hello` rust structs, i find them in 

`src/r2r_minimal_node/r2r_minimal_node/target/debug/build/r2r-0ae40d6b86d670f2/out/_r2r_generated_msgs.rs`

which is a different folder that must be used by rustc because compilation works.

why all these different directories? how to tell rust-analyzer to pick the right one?

thanks if you have answers

**Comment by huand** [comment]
ok, I made it work and will close this. You need to source the workspace with the message built so rust-analyzer can pick up the new message. What was happening is that for my rust-analyzer I had only the /opt/ros/... stuff sources, that's why I could it was building the std_msgs, but didnt have access to the new r2r_msgs, and rust-analyzer was making the dirs in target (the one without all msgs). So sourcing and restarting rust-analyzer made it works :+1:

**Comment by m-dahl** [comment]
Hi, yes as you found out it is important the you have the same environment in the your shell and for rust analyzer. Personally I use [direnv](https://direnv.net) to make sure the environment is always correctly set for my ros workspaces.
